# Database
spring:
   application:
      name: picpay_clone
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:54327/picpay_clone
      username: postgres
      password: Postgres2019!
      initialization-mode: always
   api:
      versao: 1.0.0
# JPA properties
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
   cache:
      type: redis
   redis:
      host: localhost
      port: 6379
# JWT
picpayclone:
   jwt:
      secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
      expiration: 86400000
# Actuator
management:
   endpoint:
      health:
         show-details: always
      webexposure:
         include: '*'
info:
   app:
      name: '@project.name@'
      version: '@project.version@'
      
      
